[package]
name = "raytracing"
version = "0.1.0"
authors = ["Connor <zbk602423539@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.2"
crossbeam = "0.8.0"
